/**
 * ZNPList<T> — Generic singly-linked list backed by ZNPNode<T>.
 *
 * Replaces 35 identical ZNPList_* classes previously generated by
 * createZNPList() factory in nape-compiled.js.
 *
 * Each concrete subclass must set a static `_NodeClass` property pointing
 * to the corresponding ZNPNode subclass for pool allocation.
 */
import { ZNPNode } from "./ZNPNode";

interface ZNPNodeClass<T> {
  new (): ZNPNode<T>;
  zpp_pool: ZNPNode<T> | null;
}

interface ZNPListConstructor<T> {
  _NodeClass: ZNPNodeClass<T>;
}

export class ZNPList<T> {
  static _NodeClass: ZNPNodeClass<unknown>;

  head: ZNPNode<T> | null = null;
  length: number = 0;
  modified: boolean = false;
  pushmod: boolean = false;

  private _allocNode(): ZNPNode<T> {
    const N = (this.constructor as unknown as ZNPListConstructor<T>)._NodeClass;
    let ret: ZNPNode<T>;
    if (N.zpp_pool == null) {
      ret = new N();
    } else {
      ret = N.zpp_pool;
      N.zpp_pool = ret.next;
      ret.next = null;
    }
    return ret;
  }

  private _freeNode(node: ZNPNode<T>): void {
    const N = (this.constructor as unknown as ZNPListConstructor<T>)._NodeClass;
    node.elt = null;
    node.next = N.zpp_pool;
    N.zpp_pool = node;
  }

  begin(): ZNPNode<T> | null {
    return this.head;
  }

  setbegin(i: ZNPNode<T> | null): void {
    this.head = i;
    this.modified = true;
    this.pushmod = true;
  }

  add(o: T): T {
    const node = this._allocNode();
    node.elt = o;
    node.next = this.head;
    this.head = node;
    this.modified = true;
    this.length++;
    return o;
  }

  addAll(x: ZNPList<T>): void {
    let cx_ite = x.head;
    while (cx_ite != null) {
      this.add(cx_ite.elt!);
      cx_ite = cx_ite.next;
    }
  }

  insert(cur: ZNPNode<T> | null, o: T): ZNPNode<T> {
    const node = this._allocNode();
    node.elt = o;
    if (cur == null) {
      node.next = this.head;
      this.head = node;
    } else {
      node.next = cur.next;
      cur.next = node;
    }
    this.pushmod = this.modified = true;
    this.length++;
    return node;
  }

  pop(): void {
    const ret = this.head!;
    this.head = ret.next;
    this._freeNode(ret);
    if (this.head == null) {
      this.pushmod = true;
    }
    this.modified = true;
    this.length--;
  }

  pop_unsafe(): T {
    const ret = this.head!.elt!;
    this.pop();
    return ret;
  }

  erase(pre: ZNPNode<T> | null): ZNPNode<T> | null {
    let old: ZNPNode<T>;
    let ret: ZNPNode<T> | null;
    if (pre == null) {
      old = this.head!;
      ret = old.next;
      this.head = ret;
      if (this.head == null) {
        this.pushmod = true;
      }
    } else {
      old = pre.next!;
      ret = old.next;
      pre.next = ret;
      if (ret == null) {
        this.pushmod = true;
      }
    }
    this._freeNode(old);
    this.modified = true;
    this.length--;
    this.pushmod = true;
    return ret;
  }

  remove(obj: T): void {
    let pre: ZNPNode<T> | null = null;
    let cur = this.head;
    while (cur != null) {
      if (cur.elt == obj) {
        this.erase(pre);
        break;
      }
      pre = cur;
      cur = cur.next;
    }
  }

  try_remove(obj: T): boolean {
    let pre: ZNPNode<T> | null = null;
    let cur = this.head;
    let ret = false;
    while (cur != null) {
      if (cur.elt == obj) {
        this.erase(pre);
        ret = true;
        break;
      }
      pre = cur;
      cur = cur.next;
    }
    return ret;
  }

  splice(pre: ZNPNode<T>, n: number): ZNPNode<T> | null {
    while (n-- > 0 && pre.next != null) this.erase(pre);
    return pre.next;
  }

  clear(): void {
    while (this.head != null) {
      const ret = this.head;
      this.head = ret.next;
      this._freeNode(ret);
      if (this.head == null) {
        this.pushmod = true;
      }
      this.modified = true;
      this.length--;
    }
    this.pushmod = true;
  }

  reverse(): void {
    let cur = this.head;
    let pre: ZNPNode<T> | null = null;
    while (cur != null) {
      const nx = cur.next;
      cur.next = pre;
      this.head = cur;
      pre = cur;
      cur = nx;
    }
    this.modified = true;
    this.pushmod = true;
  }

  empty(): boolean {
    return this.head == null;
  }

  size(): number {
    return this.length;
  }

  has(obj: T): boolean {
    let cx_ite = this.head;
    while (cx_ite != null) {
      if (cx_ite.elt == obj) return true;
      cx_ite = cx_ite.next;
    }
    return false;
  }

  front(): T {
    return this.head!.elt!;
  }

  back(): T {
    let ret = this.head!;
    let cur: ZNPNode<T> | null = ret;
    while (cur != null) {
      ret = cur;
      cur = cur.next;
    }
    return ret.elt!;
  }

  iterator_at(ind: number): ZNPNode<T> | null {
    let ret = this.head;
    while (ind-- > 0 && ret != null) ret = ret.next;
    return ret;
  }

  at(ind: number): T | null {
    const it = this.iterator_at(ind);
    return it != null ? it.elt : null;
  }
}

// Set inlined method aliases on prototype
ZNPList.prototype.inlined_add = ZNPList.prototype.add;
ZNPList.prototype.inlined_insert = ZNPList.prototype.insert;
ZNPList.prototype.inlined_pop = ZNPList.prototype.pop;
ZNPList.prototype.inlined_pop_unsafe = ZNPList.prototype.pop_unsafe;
ZNPList.prototype.inlined_erase = ZNPList.prototype.erase;
ZNPList.prototype.inlined_remove = ZNPList.prototype.remove;
ZNPList.prototype.inlined_try_remove = ZNPList.prototype.try_remove;
ZNPList.prototype.inlined_clear = ZNPList.prototype.clear;
ZNPList.prototype.inlined_has = ZNPList.prototype.has;

// Augment prototype type to include inlined aliases
declare module "./ZNPList" {
  interface ZNPList<T> {
    inlined_add: ZNPList<T>["add"];
    inlined_insert: ZNPList<T>["insert"];
    inlined_pop: ZNPList<T>["pop"];
    inlined_pop_unsafe: ZNPList<T>["pop_unsafe"];
    inlined_erase: ZNPList<T>["erase"];
    inlined_remove: ZNPList<T>["remove"];
    inlined_try_remove: ZNPList<T>["try_remove"];
    inlined_clear: ZNPList<T>["clear"];
    inlined_has: ZNPList<T>["has"];
  }
}
