/**
 * ZPP_Set<T> — Generic Red-Black tree set.
 *
 * Replaces 8 identical ZPP_Set_* classes previously generated by
 * createZPPSet() factory in nape-compiled.js.
 *
 * Each instance serves dual purpose: as a set container (root via `this.parent`)
 * and as individual tree nodes. New nodes are allocated from the subclass's
 * static `zpp_pool`.
 */
interface ZPP_SetConstructor<T> {
  zpp_pool: ZPP_Set<T> | null;
  new (): ZPP_Set<T>;
}

export class ZPP_Set<T> {
  static zpp_pool: ZPP_Set<unknown> | null = null;

  colour: number = 0;
  parent: ZPP_Set<T> | null = null;
  next: ZPP_Set<T> | null = null;
  prev: ZPP_Set<T> | null = null;
  data: T | null = null;
  swapped: ((a: T, b: T) => void) | null = null;
  lt: ((a: T, b: T) => boolean) | null = null;

  private _allocNode(): ZPP_Set<T> {
    const Cls = this.constructor as unknown as ZPP_SetConstructor<T>;
    let x: ZPP_Set<T>;
    if (Cls.zpp_pool == null) {
      x = new Cls();
    } else {
      x = Cls.zpp_pool;
      Cls.zpp_pool = x.next;
      x.next = null;
    }
    return x;
  }

  private _freeNode(node: ZPP_Set<T>): void {
    const Cls = this.constructor as unknown as ZPP_SetConstructor<T>;
    node.data = null;
    node.lt = null;
    node.swapped = null;
    node.next = Cls.zpp_pool;
    Cls.zpp_pool = node;
  }

  free(): void {
    this.data = null;
    this.lt = null;
    this.swapped = null;
  }

  alloc(): void {}

  verify(): boolean {
    if (!this.empty()) {
      let set_ite: ZPP_Set<T> | null = this.parent;
      while (set_ite!.prev != null) set_ite = set_ite!.prev;
      while (set_ite != null) {
        const i = set_ite.data!;
        let prei = true;
        if (!this.empty()) {
          let set_ite1: ZPP_Set<T> | null = this.parent;
          while (set_ite1!.prev != null) set_ite1 = set_ite1!.prev;
          while (set_ite1 != null) {
            const j = set_ite1.data!;
            if (!prei) {
              if (!this.lt!(i, j) && this.lt!(j, i)) return false;
            } else if (i == j) {
              prei = false;
            } else if (!this.lt!(j, i) && this.lt!(i, j)) return false;
            if (set_ite1.next != null) {
              set_ite1 = set_ite1.next;
              while (set_ite1!.prev != null) set_ite1 = set_ite1!.prev;
            } else {
              while (set_ite1!.parent != null && set_ite1 == set_ite1!.parent!.next)
                set_ite1 = set_ite1!.parent;
              set_ite1 = set_ite1!.parent;
            }
          }
        }
        if (set_ite.next != null) {
          set_ite = set_ite.next;
          while (set_ite!.prev != null) set_ite = set_ite!.prev;
        } else {
          while (set_ite!.parent != null && set_ite == set_ite!.parent!.next)
            set_ite = set_ite!.parent;
          set_ite = set_ite!.parent;
        }
      }
    }
    return true;
  }

  empty(): boolean {
    return this.parent == null;
  }

  singular(): boolean {
    if (this.parent != null && this.parent.prev == null) return this.parent.next == null;
    return false;
  }

  size(): number {
    let ret = 0;
    if (!this.empty()) {
      let set_ite: ZPP_Set<T> | null = this.parent;
      while (set_ite!.prev != null) set_ite = set_ite!.prev;
      while (set_ite != null) {
        ++ret;
        if (set_ite.next != null) {
          set_ite = set_ite.next;
          while (set_ite!.prev != null) set_ite = set_ite!.prev;
        } else {
          while (set_ite!.parent != null && set_ite == set_ite!.parent!.next)
            set_ite = set_ite!.parent;
          set_ite = set_ite!.parent;
        }
      }
    }
    return ret;
  }

  has(obj: T): boolean {
    return this.find(obj) != null;
  }

  find(obj: T): ZPP_Set<T> | null {
    let cur = this.parent;
    while (cur != null && cur.data != obj) {
      if (this.lt!(obj, cur.data!)) cur = cur.prev;
      else cur = cur.next;
    }
    return cur;
  }

  has_weak(obj: T): boolean {
    return this.find_weak(obj) != null;
  }

  find_weak(obj: T): ZPP_Set<T> | null {
    let cur = this.parent;
    while (cur != null) {
      if (this.lt!(obj, cur.data!)) cur = cur.prev;
      else if (this.lt!(cur.data!, obj)) cur = cur.next;
      else break;
    }
    return cur;
  }

  lower_bound(obj: T): T | null {
    let ret: T | null = null;
    if (!this.empty()) {
      let set_ite: ZPP_Set<T> | null = this.parent;
      while (set_ite!.prev != null) set_ite = set_ite!.prev;
      while (set_ite != null) {
        if (!this.lt!(set_ite.data!, obj)) {
          ret = set_ite.data;
          break;
        }
        if (set_ite.next != null) {
          set_ite = set_ite.next;
          while (set_ite!.prev != null) set_ite = set_ite!.prev;
        } else {
          while (set_ite!.parent != null && set_ite == set_ite!.parent!.next)
            set_ite = set_ite!.parent;
          set_ite = set_ite!.parent;
        }
      }
    }
    return ret;
  }

  first(): T {
    let cur = this.parent!;
    while (cur.prev != null) cur = cur.prev;
    return cur.data!;
  }

  pop_front(): T {
    let cur = this.parent!;
    while (cur.prev != null) cur = cur.prev;
    const ret = cur.data!;
    this.remove_node(cur);
    return ret;
  }

  remove(obj: T): void {
    this.remove_node(this.find(obj)!);
  }

  successor_node(cur: ZPP_Set<T>): ZPP_Set<T> | null {
    if (cur.next != null) {
      cur = cur.next;
      while (cur.prev != null) cur = cur.prev;
    } else {
      let pre = cur;
      cur = cur.parent!;
      while (cur != null && cur.prev != pre) {
        pre = cur;
        cur = cur.parent!;
      }
    }
    return cur;
  }

  predecessor_node(cur: ZPP_Set<T>): ZPP_Set<T> | null {
    if (cur.prev != null) {
      cur = cur.prev;
      while (cur.next != null) cur = cur.next;
    } else {
      let pre = cur;
      cur = cur.parent!;
      while (cur != null && cur.next != pre) {
        pre = cur;
        cur = cur.parent!;
      }
    }
    return cur;
  }

  successor(obj: T): T | null {
    const node = this.successor_node(this.find(obj)!);
    return node == null ? null : node.data;
  }

  predecessor(obj: T): T | null {
    const node = this.predecessor_node(this.find(obj)!);
    return node == null ? null : node.data;
  }

  remove_node(cur: ZPP_Set<T>): void {
    if (cur.next != null && cur.prev != null) {
      let sm = cur.next;
      while (sm.prev != null) sm = sm.prev;
      const t = cur.data;
      cur.data = sm.data;
      sm.data = t;
      if (this.swapped != null) this.swapped(cur.data!, sm.data!);
      cur = sm;
    }
    const child = cur.prev == null ? cur.next : cur.prev;
    if (cur.colour == 1) {
      if (cur.prev != null || cur.next != null) {
        child!.colour = 1;
      } else if (cur.parent != null) {
        let parent: ZPP_Set<T> = cur.parent;
        while (true) {
          parent.colour++;
          parent.prev!.colour--;
          parent.next!.colour--;
          const child1 = parent.prev!;
          if (child1.colour == -1) {
            this.__fix_neg_red(child1);
            break;
          } else if (child1.colour == 0) {
            if (child1.prev != null && child1.prev.colour == 0) {
              this.__fix_dbl_red(child1.prev);
              break;
            }
            if (child1.next != null && child1.next.colour == 0) {
              this.__fix_dbl_red(child1.next);
              break;
            }
          }
          const child2 = parent.next!;
          if (child2.colour == -1) {
            this.__fix_neg_red(child2);
            break;
          } else if (child2.colour == 0) {
            if (child2.prev != null && child2.prev.colour == 0) {
              this.__fix_dbl_red(child2.prev);
              break;
            }
            if (child2.next != null && child2.next.colour == 0) {
              this.__fix_dbl_red(child2.next);
              break;
            }
          }
          if (parent.colour == 2) {
            if (parent.parent == null) {
              parent.colour = 1;
            } else {
              parent = parent.parent;
              continue;
            }
          }
          break;
        }
      }
    }
    const par = cur.parent;
    if (par == null) this.parent = child;
    else if (par.prev == cur) par.prev = child;
    else par.next = child;
    if (child != null) child.parent = par;
    cur.parent = cur.prev = cur.next = null;
    this._freeNode(cur);
  }

  clear(): void {
    if (this.parent != null) {
      let cur: ZPP_Set<T> | null = this.parent;
      while (cur != null) {
        if (cur.prev != null) cur = cur.prev;
        else if (cur.next != null) cur = cur.next;
        else {
          const ret: ZPP_Set<T> | null = cur.parent;
          if (ret != null) {
            if (cur == ret.prev) ret.prev = null;
            else ret.next = null;
            cur.parent = null;
          }
          this._freeNode(cur);
          cur = ret;
        }
      }
      this.parent = null;
    }
  }

  clear_with(lambda: (data: T) => void): void {
    if (this.parent == null) return;
    let cur: ZPP_Set<T> | null = this.parent;
    while (cur != null) {
      if (cur.prev != null) cur = cur.prev;
      else if (cur.next != null) cur = cur.next;
      else {
        lambda(cur.data!);
        const ret: ZPP_Set<T> | null = cur.parent;
        if (ret != null) {
          if (cur == ret.prev) ret.prev = null;
          else ret.next = null;
          cur.parent = null;
        }
        this._freeNode(cur);
        cur = ret;
      }
    }
    this.parent = null;
  }

  clear_node(node: ZPP_Set<T>, lambda: (data: T) => void): ZPP_Set<T> | null {
    lambda(node.data!);
    const ret = node.parent;
    if (ret != null) {
      if (node == ret.prev) ret.prev = null;
      else ret.next = null;
      node.parent = null;
    }
    this._freeNode(node);
    return ret;
  }

  __fix_neg_red(negred: ZPP_Set<T>): void {
    const parent = negred.parent!;
    let child: ZPP_Set<T>;
    if (parent.prev == negred) {
      const nl = negred.prev!;
      const nr = negred.next!;
      const trl = nr.prev;
      const trr = nr.next;
      nl.colour = 0;
      negred.colour = parent.colour = 1;
      negred.next = trl;
      if (trl != null) trl.parent = negred;
      const t = parent.data;
      parent.data = nr.data;
      nr.data = t;
      if (this.swapped != null) this.swapped(parent.data!, nr.data!);
      nr.prev = trr;
      if (trr != null) trr.parent = nr;
      nr.next = parent.next;
      if (parent.next != null) parent.next.parent = nr;
      parent.next = nr;
      if (nr != null) nr.parent = parent;
      child = nl;
    } else {
      const nl1 = negred.next!;
      const nr1 = negred.prev!;
      const trl1 = nr1.next;
      const trr1 = nr1.prev;
      nl1.colour = 0;
      negred.colour = parent.colour = 1;
      negred.prev = trl1;
      if (trl1 != null) trl1.parent = negred;
      const t1 = parent.data;
      parent.data = nr1.data;
      nr1.data = t1;
      if (this.swapped != null) this.swapped(parent.data!, nr1.data!);
      nr1.next = trr1;
      if (trr1 != null) trr1.parent = nr1;
      nr1.prev = parent.prev;
      if (parent.prev != null) parent.prev.parent = nr1;
      parent.prev = nr1;
      if (nr1 != null) nr1.parent = parent;
      child = nl1;
    }
    if (child.prev != null && child.prev.colour == 0) this.__fix_dbl_red(child.prev);
    else if (child.next != null && child.next.colour == 0) this.__fix_dbl_red(child.next);
  }

  __fix_dbl_red(x: ZPP_Set<T>): void {
    while (true) {
      const par = x.parent!;
      const g = par.parent;
      if (g == null) {
        par.colour = 1;
        break;
      }
      let n1: ZPP_Set<T>, n2: ZPP_Set<T>, n3: ZPP_Set<T>;
      let t1: ZPP_Set<T> | null, t2: ZPP_Set<T> | null;
      let t3: ZPP_Set<T> | null, t4: ZPP_Set<T> | null;
      if (par == g.prev) {
        n3 = g;
        t4 = g.next;
        if (x == par.prev) {
          n1 = x;
          n2 = par;
          t1 = x.prev;
          t2 = x.next;
          t3 = par.next;
        } else {
          n1 = par;
          n2 = x;
          t1 = par.prev;
          t2 = x.prev;
          t3 = x.next;
        }
      } else {
        n1 = g;
        t1 = g.prev;
        if (x == par.prev) {
          n2 = x;
          n3 = par;
          t2 = x.prev;
          t3 = x.next;
          t4 = par.next;
        } else {
          n2 = par;
          n3 = x;
          t2 = par.prev;
          t3 = x.prev;
          t4 = x.next;
        }
      }
      const par1 = g.parent;
      if (par1 == null) this.parent = n2;
      else if (par1.prev == g) par1.prev = n2;
      else par1.next = n2;
      if (n2 != null) n2.parent = par1;
      n1.prev = t1;
      if (t1 != null) t1.parent = n1;
      n1.next = t2;
      if (t2 != null) t2.parent = n1;
      n2.prev = n1;
      if (n1 != null) n1.parent = n2;
      n2.next = n3;
      if (n3 != null) n3.parent = n2;
      n3.prev = t3;
      if (t3 != null) t3.parent = n3;
      n3.next = t4;
      if (t4 != null) t4.parent = n3;
      n2.colour = g.colour - 1;
      n1.colour = 1;
      n3.colour = 1;
      if (n2 == this.parent) {
        this.parent!.colour = 1;
      } else if (n2.colour == 0 && n2.parent!.colour == 0) {
        x = n2;
        continue;
      }
      break;
    }
  }

  try_insert_bool(obj: T): boolean {
    let x: ZPP_Set<T> | null = null;
    if (this.parent == null) {
      x = this._allocNode();
      x.data = obj;
      this.parent = x;
    } else {
      let cur: ZPP_Set<T> = this.parent;
      while (true) {
        if (this.lt!(obj, cur.data!)) {
          if (cur.prev == null) {
            x = this._allocNode();
            x.data = obj;
            cur.prev = x;
            x.parent = cur;
            break;
          } else cur = cur.prev;
        } else if (this.lt!(cur.data!, obj)) {
          if (cur.next == null) {
            x = this._allocNode();
            x.data = obj;
            cur.next = x;
            x.parent = cur;
            break;
          } else cur = cur.next;
        } else break;
      }
    }
    if (x == null) return false;
    if (x.parent == null) x.colour = 1;
    else {
      x.colour = 0;
      if (x.parent.colour == 0) this.__fix_dbl_red(x);
    }
    return true;
  }

  try_insert(obj: T): ZPP_Set<T> | null {
    let x: ZPP_Set<T> | null = null;
    let cur: ZPP_Set<T> | null = null;
    if (this.parent == null) {
      x = this._allocNode();
      x.data = obj;
      this.parent = x;
    } else {
      cur = this.parent;
      while (true) {
        if (this.lt!(obj, cur!.data!)) {
          if (cur!.prev == null) {
            x = this._allocNode();
            x.data = obj;
            cur!.prev = x;
            x.parent = cur;
            break;
          } else cur = cur!.prev;
        } else if (this.lt!(cur!.data!, obj)) {
          if (cur!.next == null) {
            x = this._allocNode();
            x.data = obj;
            cur!.next = x;
            x.parent = cur;
            break;
          } else cur = cur!.next;
        } else break;
      }
    }
    if (x == null) return cur;
    if (x.parent == null) x.colour = 1;
    else {
      x.colour = 0;
      if (x.parent.colour == 0) this.__fix_dbl_red(x);
    }
    return x;
  }

  insert(obj: T): ZPP_Set<T> {
    const x = this._allocNode();
    x.data = obj;
    if (this.parent == null) {
      this.parent = x;
    } else {
      let cur = this.parent;
      while (true) {
        if (this.lt!(x.data!, cur.data!)) {
          if (cur.prev == null) {
            cur.prev = x;
            x.parent = cur;
            break;
          } else cur = cur.prev;
        } else if (cur.next == null) {
          cur.next = x;
          x.parent = cur;
          break;
        } else cur = cur.next;
      }
    }
    if (x.parent == null) x.colour = 1;
    else {
      x.colour = 0;
      if (x.parent.colour == 0) this.__fix_dbl_red(x);
    }
    return x;
  }
}
